#!/bin/bash

# Install pyenv and install version 3.10.14
echo "Installing pyenv..."
sudo pacman -S pyenv
echo "Done"
echo "Installing python 3.10.14..."
pyenv install 3.10.14
pyenv local 3.10.14
echo "Done"
echo "Installing python packages..."
pyenv exec python3.10 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
echo "Done"
# Install yosys
echo "Installing yosys..."
sudo pacman -S yosys
echo "Done"
# Install vtr
echo "Installing VTR..."
git clone https://github.com/verilog-to-routing/vtr-verilog-to-routing.git
cd vtr-verilog-to-routing
make -j$(nproc)
cd ..
echo "Done"
# Install icarus verilog
echo "Installing icarus verilog..."
sudo pacman -S iverilog
sudo pacman -S gtkwave
echo "Done"
# Create directory for build files
mkdir -p fpga/build
echo "Setup complete"
